import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15
import Qt.labs.platform 1.1

ApplicationWindow {
    id: window
    visible: true
    width: 360
    height: 640
    title: "Other Apps"
    color: "#1a1a2e"

    // Dynamic paths based on environment
    property string homeDir: StandardPaths.writableLocation(StandardPaths.HomeLocation)
    property string stateDir: homeDir + "/.local/state/flick-phosh"
    property string userAppsDir: homeDir + "/.local/share/applications"
    property string systemAppsDir: "/usr/share/applications"

    // App model - populated from config file
    ListModel {
        id: appsModel
    }

    Component.onCompleted: {
        loadApps()
    }

    function loadApps() {
        // Load apps from the curated list (dynamically generated by phosh-icon-manager)
        var xhr = new XMLHttpRequest()
        var configPath = stateDir + "/curated_other_apps.json"

        xhr.open("GET", "file://" + configPath, false)
        xhr.send()

        if (xhr.status === 200 || xhr.status === 0) {
            try {
                var apps = JSON.parse(xhr.responseText)
                for (var i = 0; i < apps.length; i++) {
                    var appId = apps[i]
                    var appInfo = getAppInfo(appId)
                    if (appInfo) {
                        appsModel.append(appInfo)
                    }
                }
            } catch (e) {
                console.log("Error parsing config: " + e)
                showError("No apps configured.\nUse: phosh-icon-manager curate <app_id>")
            }
        } else {
            showError("No apps configured.\nUse: phosh-icon-manager curate <app_id>")
        }
    }

    function showError(msg) {
        errorText.text = msg
        errorText.visible = true
    }

    function getAppInfo(appId) {
        // Try to read .desktop file to get app info - check user dir first, then system
        var paths = [
            userAppsDir + "/" + appId + ".desktop",
            systemAppsDir + "/" + appId + ".desktop"
        ]

        for (var i = 0; i < paths.length; i++) {
            var xhr = new XMLHttpRequest()
            xhr.open("GET", "file://" + paths[i], false)
            xhr.send()

            if (xhr.status === 200 || xhr.status === 0 && xhr.responseText) {
                var lines = xhr.responseText.split("\n")
                var name = appId
                var icon = "application-x-executable"
                var exec = ""

                for (var j = 0; j < lines.length; j++) {
                    var line = lines[j].trim()
                    if (line.indexOf("Name=") === 0 && name === appId) {
                        name = line.substring(5)
                    } else if (line.indexOf("Icon=") === 0) {
                        icon = line.substring(5)
                    } else if (line.indexOf("Exec=") === 0 && !exec) {
                        exec = line.substring(5).replace(/%[uUfF]/g, "").trim()
                    }
                }

                if (exec) {
                    return {appId: appId, name: name, icon: icon, exec: exec}
                }
            }
        }
        return null
    }

    function launchApp(exec) {
        console.log("Launching: " + exec)
        launcher.start("sh", ["-c", exec])
        // Close folder after launching
        Qt.quit()
    }

    Process {
        id: launcher
    }

    // Header
    Rectangle {
        id: header
        anchors.top: parent.top
        anchors.left: parent.left
        anchors.right: parent.right
        height: 60
        color: "#16213e"

        RowLayout {
            anchors.fill: parent
            anchors.margins: 10

            Button {
                text: "<"
                font.pixelSize: 24
                background: Rectangle { color: "transparent" }
                contentItem: Text {
                    text: parent.text
                    color: "white"
                    font: parent.font
                }
                onClicked: Qt.quit()
            }

            Text {
                text: "Other Apps"
                color: "white"
                font.pixelSize: 20
                font.bold: true
                Layout.fillWidth: true
                horizontalAlignment: Text.AlignHCenter
            }

            Item { width: 40 }
        }
    }

    // App Grid
    GridView {
        id: gridView
        anchors.top: header.bottom
        anchors.left: parent.left
        anchors.right: parent.right
        anchors.bottom: parent.bottom
        anchors.margins: 20

        cellWidth: width / 3
        cellHeight: 120

        model: appsModel

        delegate: Item {
            width: gridView.cellWidth
            height: gridView.cellHeight

            Column {
                anchors.centerIn: parent
                spacing: 8

                Rectangle {
                    width: 64
                    height: 64
                    radius: 16
                    color: "#2d3561"
                    anchors.horizontalCenter: parent.horizontalCenter

                    Image {
                        anchors.centerIn: parent
                        width: 48
                        height: 48
                        source: "image://icon/" + model.icon
                        sourceSize: Qt.size(48, 48)
                        fillMode: Image.PreserveAspectFit

                        // Fallback if icon not found
                        onStatusChanged: {
                            if (status === Image.Error) {
                                source = ""
                            }
                        }
                    }

                    Text {
                        anchors.centerIn: parent
                        text: model.name.charAt(0).toUpperCase()
                        color: "white"
                        font.pixelSize: 24
                        font.bold: true
                        visible: parent.children[0].status === Image.Error || parent.children[0].source === ""
                    }

                    MouseArea {
                        anchors.fill: parent
                        onClicked: launchApp(model.exec)
                        onPressed: parent.color = "#4a5899"
                        onReleased: parent.color = "#2d3561"
                    }
                }

                Text {
                    text: model.name
                    color: "white"
                    font.pixelSize: 12
                    width: gridView.cellWidth - 10
                    horizontalAlignment: Text.AlignHCenter
                    elide: Text.ElideRight
                    anchors.horizontalCenter: parent.horizontalCenter
                }
            }
        }
    }

    // Empty/error state
    Text {
        id: errorText
        anchors.centerIn: parent
        text: "No other apps configured.\nUse: phosh-icon-manager curate <app_id>"
        color: "#888"
        font.pixelSize: 14
        horizontalAlignment: Text.AlignHCenter
        visible: appsModel.count === 0
    }
}
